### ISSUE TITLE
Single image for both master and slave

### ISSUE THREAD

**Issue by jeanminet** [tknopp/RedPitayaDAQServer#2]
Hello,

I was wondering if it was possible to use the same bitstream for both master and slave.
Would this connection work ? :

![screenshot from 2017-10-04 13-09-07](https://user-images.githubusercontent.com/1735094/31172761-20d6feb8-a905-11e7-9189-d6a781826695.png)

Best,
Jean

**Comment by tknopp** [comment]
Hi Jean, it would be really great if this would be possible. I just know that Jonas tried something which did not work. He meant that the issue is, that the slave has no clock at that time when this decision was made.
I cannot comment on the FPGA stuff since I only did the entire C stuff. Ping @jbeuke therefore.

**Comment by jbeuke** [comment]
@jeanminet My first idea was to expose the master/slave settings to the cpu via a configuration register. This did not work, since I need a clock for the register which I don't get, if the clock selection is wrong. Your idea is actually a really nice one since the locked output of clk_wiz_1 should only be high if a clock is supplied via the daisy chain connector. I will add this to the blockdesign and have @tknopp test it in hardware ;)

**Comment by tknopp** [comment]
yes sure, I can test. You could make a branch that I can test.

**Comment by jbeuke** [comment]
Apparently, this does not work as expected. The acquisition pointer sometimes stops or jumps, which makes the acquisition unreliable. Since using two different bitfiles for master and slave is not a major issue, I postpone digging further for a solution. Help is appreciated though!

**Comment by mgraeser** [comment]
I included the following solution to the branch v2:
![image](https://user-images.githubusercontent.com/24937954/78472609-9a5fce80-773a-11ea-83eb-2fad8da20878.png)
The select is driven bei ext_DIO0_N. On the other side of the BlockDiagram ext_DIO1_N is given a constant 0. Now the DIO0_N is physically between a high (3.3V on External conn) and low (DIO1_N).
With a jumper between DIO1_N and DIO_0_N the device is set as Master. Between 3.3V and DIO0_N it is set to slave. 
The advantage here is that the DIOs do not need the clock to work.
