### ISSUE TITLE
Compatible with STEMlab 122.88-16 device

### ISSUE THREAD

**Issue by ashindin** [tknopp/RedPitayaDAQServer#21]
Hello,
what changes are required to the project to be compatible with new STEMlab 122.88-16?

Unfortunately, the project cannot be made with the latest version of the development machine from Pavel Demin with Vivado 2018.3 (version 2017.2 required). I will try to do it with the older version.

Is it possible (in principle) to add DDCs to the FPGA design for tuning to the specific frequency and get the IQ samples at this central frequency with decimation 8?

Best regards, 
Alexey.

**Comment by jbeuke** [comment]
Hi Alexey,

try changing https://github.com/tknopp/RedPitayaDAQServer/blob/master/src/fpga/bd/bd.tcl#L23 to the correct Vivado version. This could maybe work with 2018.3. Since I do not have access to a STEMlab 122.88-16 I cannot comment on the compatability. My guess would be that by changing the appropriate values in the blockdesign (clock generators, DDS compilers etc.) it should work. Maybe the server would also need a few changes. Adding processing steps prior to streaming the data to RAM should be rather easy. Actually, I think I am already using a DDC for decimating the data.

It would be nice to hear if the project works for you. Maybe we can include the device somehow and support both versions of STEMlab

Cheers
Jonas
